import 'package:flutter/material.dart';

class AppStrings {
  AppStrings._();
  static final String my_pr = 'My Prepaid';
  static final String num = '092787368820';
  static final String recommended = 'Recommended';
  static final String viewAll = 'View All';
  static final String cardSelected = 'Load Balance';
  static final String selectedPrice = 'P 1675.00';
  static final String selectedValidity = 'Valid till 26 Dec';
  static final String balance = 'Data Balance';
  static final String dataBalance = '300MB';
  static final String totalBalance = 'of 12 GB';
  static final String event_1 = 'GoUNLI350';
  static final String event_1_time = '30 days UNLI to Globe';
  static final String event_2 = 'GoUNLI180';
  static final String event_2_time = '15 days UNLI to Globe';
  static final String specialPromos = 'Special Promos';
  static final String goSakto = 'GoSakto';
  static final String spText = 'Create What Matters';
  static final String spDis = "Pomo that's all for you!";
  static final String spconc = 'Create your own Promo';
  static final String latestPromos = 'Latest Promos';
  static final String lSpotify = 'Spotify';
  static final String lsPremium = ' Premium';
  static final String lSubscription = 'Subscribe for';
  static final String lPrice = 'P 129.00';
  static final String lperM = '  /m';
  static final String lFacebook = 'Facebook';
  static final String lSurf = ' Surf';
  static final String lfText = 'Get Pack for';
  static final String lfPrice = 'P 50.00';
  static final String roamingPlans = 'Roaming Plans';
  static final String rText = 'Planning for a foreign trip?';
  static final String rdis = 'Roam worry free!';
  static final String rconc = 'Explore Roaming Packs';
  static final String globeRewards = 'Globe Rewards';
  static final String gText = 'YOUR REWARD POINTS';
  static final String greward = '7250';
  static final String gpts = ' Pts';
  static final String offerText = '    Here is what you can get';
  static final String thousand = '1000';
  static final String priceShoes = 'P 500 OFF';
  static final String offerSh = 'on Shoes';
  static final String sp1 = 'Get Hair Spa';
  static final String sp2 = '& Styling';
  static final String fOM = 'Find Out More';
  static final String mySub = 'My Subscriptions';
  static final String remainingGb = 'With Remaining 12GB,';
  static final String reaminingMin = 'You can watch 640 min of video';
  static final String popularOn = 'Popular on';
  static final String latestOn = 'Latest on';
  static final String etc = 'You might also like';
}
